-- Fix organization_members.organization_id FK:
-- Originally referenced partners(id) but should reference organizations(id)
-- for the multi-tenant architecture used by create-company-signup.

-- Drop the old FK constraint (name auto-generated by Postgres)
DO $$ BEGIN
  ALTER TABLE public.organization_members
    DROP CONSTRAINT IF EXISTS organization_members_organization_id_fkey;
EXCEPTION WHEN OTHERS THEN NULL;
END $$;

-- Also try alternate constraint name patterns Postgres may have generated
DO $$ BEGIN
  ALTER TABLE public.organization_members
    DROP CONSTRAINT IF EXISTS "organization_members_organization_id_fkey1";
EXCEPTION WHEN OTHERS THEN NULL;
END $$;

-- Change organization_id to allow nulls temporarily so we can alter constraint
-- (only needed if existing rows violate the new FK — on a fresh project there are none)

-- Add new FK constraint pointing to organizations
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints tc
    JOIN information_schema.key_column_usage kcu
      ON tc.constraint_name = kcu.constraint_name
    JOIN information_schema.referential_constraints rc
      ON tc.constraint_name = rc.constraint_name
    JOIN information_schema.table_constraints tc2
      ON rc.unique_constraint_name = tc2.constraint_name
    WHERE tc.table_name = 'organization_members'
      AND tc.constraint_type = 'FOREIGN KEY'
      AND kcu.column_name = 'organization_id'
      AND tc2.table_name = 'organizations'
  ) THEN
    ALTER TABLE public.organization_members
      ADD CONSTRAINT organization_members_organization_id_fkey
      FOREIGN KEY (organization_id) REFERENCES public.organizations(id) ON DELETE CASCADE;
  END IF;
EXCEPTION WHEN OTHERS THEN NULL;
END $$;

-- Ensure role column accepts TEXT (in case it's still constrained to old enum values only)
-- The app_role enum now includes super_admin, org_admin, admin, ops_manager, etc.
-- Add all needed values idempotently:
DO $$ BEGIN
  ALTER TYPE public.app_role ADD VALUE IF NOT EXISTS 'org_admin';
EXCEPTION WHEN OTHERS THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TYPE public.app_role ADD VALUE IF NOT EXISTS 'ops_manager';
EXCEPTION WHEN OTHERS THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TYPE public.app_role ADD VALUE IF NOT EXISTS 'finance_manager';
EXCEPTION WHEN OTHERS THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TYPE public.app_role ADD VALUE IF NOT EXISTS 'sales_rep';
EXCEPTION WHEN OTHERS THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TYPE public.app_role ADD VALUE IF NOT EXISTS 'standard';
EXCEPTION WHEN OTHERS THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TYPE public.app_role ADD VALUE IF NOT EXISTS 'customer';
EXCEPTION WHEN OTHERS THEN NULL;
END $$;

-- Ensure organization_members.role can store TEXT (change type if still enum-only)
-- We ALTER to TEXT so any role string can be stored without enum maintenance overhead.
DO $$ BEGIN
  ALTER TABLE public.organization_members
    ALTER COLUMN role TYPE TEXT USING role::TEXT;
EXCEPTION WHEN OTHERS THEN NULL;
END $$;
